by Suman Kumar Bera <br>
Email id: skbera.iitkgp21@gmail.com <br>
LinkedIn: [skbera4](https://www.linkedin.com/in/skbera4/)

In [1]:
!python Tushar_Kutal.py 0.43

zsh:1: command not found: python


In [2]:
print(91)
type(print("9"))


91
9


NoneType

1. Hands on Python: Notebook(Colab, Jupyter) 1st November, 2025 (11:30 - 01:00)

### Notebooks
1. jupyter
2. Colab

jupyter, download Anaconda and install it <br>

Download link: [Anaconda](https://www.anaconda.com/download/)

Google Colab link: [Colab](https://colab.research.google.com/)

- Print Statement
- Variables
- Formatted String
- Input from user

In [3]:
# print statement

print(911)
print("9")

911
9


### Variables in Python

- integer
- floating point
- string
- boolean
- and many more

In [4]:
bucket = 15  #variable is 'bucket', data is 15 and the type of data is int
print(bucket)  #() #=

15


In [5]:
float_bucket = 15.443
print(float_bucket)
round(float_bucket, 1)

15.443


15.4

In [6]:
container = 7.5
type(container) #type()

float

In [7]:
# F-string

#An f-string (formatted string literal) in Python is a way to embed expressions (like variables or calculations)
#directly inside a string, making string formatting cleaner and more readable.

# you need to use this

name = "Alice"
age = 25

print(f"The type of age is: {type(age)}")

message = f"My name is {name} and I am {age} years old."
print(message)


The type of age is: <class 'int'>
My name is Alice and I am 25 years old.


In [8]:
# Input from user in Python

#round()
#type()
#input()

name = input('Hi! what is your name:')

print(f'Hello {name}, how are you?')

Hello krushna, how are you?


In [9]:
# Ask the price of two products from the user and tell the user the total price

first_product_price = input('What is the price of the first prodcut?')

second_prodcut_price = input('What is the price of the second product?')

total_price = first_product_price + second_prodcut_price

print(f'The total price of the products is: {total_price}')

The total price of the products is: 1212


In [12]:
price_in_int=int(first_product_price)+int(second_prodcut_price)
print("The total price of the two products is: ",price_in_int)

The total price of the two products is:  24


In [ ]:
type(first_product_price)

In [ ]:
# Ask the price of two products from the user and tell the user the total price
#float(input())
first_product_price = float(input('What is the price of the first prodcut?'))

second_prodcut_price = float(input('What is the price of the second product?'))

total_price = first_product_price + second_prodcut_price

print(f'The total price of the products is: {total_price}')

In [ ]:
type(first_product_price)

### List

In [ ]:
# List

list_a = ["banana", "apple", "mango", "mango"] # (), {}, [] #round()
print(list_a)

1. Rice
2. Lentils
3. Atta
4. Curd

In [14]:
list_grocery = ["Rice", "Lentils", "Atta", "Curd"]
print(list_grocery)

['Rice', 'Lentils', 'Atta', 'Curd']


In [16]:
list_grocery[3]

'Curd'

In [17]:
for i, item in enumerate(list_grocery):
  print(f"{i}th item is: {item}")

0th item is: Rice
1th item is: Lentils
2th item is: Atta
3th item is: Curd


In [18]:
for item in range(50, 150, 30): #range(15), 0-14 # v.IMP range()
  print(item) #range(start, end, skip)

50
80
110
140


In [19]:

set_a = set(["banana", "apple", "mango", "mango"]) #float(input())
set_a

{'apple', 'banana', 'mango'}

In [20]:

type(set_a)

set

In [22]:
list_a

NameError: name 'list_a' is not defined

In [23]:
list_b = ["biscuit", "cake"]
# print(list_a + list_b)
list_c = list_a + list_b
print(list_c)

NameError: name 'list_a' is not defined

In [ ]:
for item in list_c:
    print(item)

In [ ]:

len(list_c) #len()

In [ ]:
list_grocery[0]

In [24]:
# list_of_numbers = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
list_of_numbers = list(range(10, 20))

for i in range(0, len(list_of_numbers), 1):
    print(list_of_numbers[i])


10
11
12
13
14
15
16
17
18
19


In [25]:
st = "pYThon"
print(st.upper())
print(st.lower())
print(st)

PYTHON
python
pYThon


In [26]:
st = "$100"
st_new = st.replace("$", "")
type(st_new)
st_new = float(st_new)
st_new

100.0

### If-Else

✅ If-Else Statements
if, elif, and else are used to make decisions in your program. The condition inside if is evaluated — if it’s True, that block runs. If not, Python checks the elif condition. If none are true, else runs.

In [27]:
x = 10

if x > 0:
    print("Positive number")
elif x == 0: # x=3
    print("Zero")
else:
    print("Negative number")


Positive number


🔁 While Loop
A while loop repeats a block of code as long as a condition is True. It's useful when the number of iterations is not fixed.

In [ ]:
count = 0

while count < 13: #while condition is true, execute this loop
    print("Count is:", count)
    count += 1


🔁 For Loop
A for loop is used to iterate over a sequence like a list, string, or range. It's ideal when you know in advance how many times to loop.

In [ ]:
fruits = ["apple", "banana", "grapes"]

for fruit in fruits:
    print(f"I like: {fruit}")


In [ ]:
s = 0  # start with a sum of 0

# for some range square the numbers and sum them up and store in "s"
#s = 1**2 + 2**2 + 3**2
#s = 1 + 4 + 9
#s = 14

for i in range(1, 4):  # loop from 1 to 3 # base**power, A*B
    term = i ** 2       # raise i to the power of 2 (square it)
    s += term           # add the term to the sum s = s + term
    print(f"After adding {i}**2 = {term}, total = {s}")

print("Final sum:", s)


## Python Function
A function is a block of code which only runs when it is called.

You can pass data, known as parameters, into a function.

A function can return data as a result.

In [ ]:
name_of_function(15)

In [ ]:
name_of_function(15)

In [28]:
def countdown(n):
    if n == 0:
        print("Happy New Year!")   # Base case
    else:
        print(f"{n} seconds remaining")
        countdown(n - 1)      # Recursive call


In [29]:
countdown(10)

10 seconds remaining
9 seconds remaining
8 seconds remaining
7 seconds remaining
6 seconds remaining
5 seconds remaining
4 seconds remaining
3 seconds remaining
2 seconds remaining
1 seconds remaining
Happy New Year!


In [ ]:
def factorial(n): # 4! = 4 * 3 * 2 * 1!
    if n == 1:
        return 1
    else:
        return n * factorial(n - 1)


In [ ]:
factorial(4)

In [ ]:
def functions():
  #modify
  # write everything here
if __name__ == "__main__":
    ip = int(sys.argv[1])
    print(series(ip))

In [ ]:
import sys

def frac(i):
  fact = 1
  while i > 0:
    fact = fact * i
    i = i-1
  return fact
frac(4)

In [ ]:
d= []
for j in range(1,i+1):
  k = frac(j)**2/(frac(j) + j)
  d.append(k)

result = float(d[0]- d[1] + d[2])
print(f'{result:.2f}')

In [ ]:
import sys
def frac(i):
  fact = 1
  while i>0:
    fact = fact * i
    i = i-1
  return fact

def series(ip):
  results = []
  for i in range(1, ip+1):
    total = frac(i)**2/(frac(i)+i)
    results.append(total)
  final_result = results[0] - results[1] + results[2]
  return final_result

# if __name__ == "__main__":
#   ip = int(sys.argv[1])
print(series(ip))


In [ ]:
import numpy as np

In [ ]:
#List = ["banaan", "orange", '''']
#List = [1, 2, 3, 4]
import numpy as np
array_1d = np.array([1, 2, 3, 4, 5])  # () [] {} [1, 2, 3, 4, 5]
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) #Matrix
print(f"1D Array:{array_1d}")
print(f"2D Array:\n{array_2d}")

In [ ]:
print(f"Shape: {array_2d.shape}") # (3,3) #(rows, columns)
print(f"Data Type: {array_2d.dtype}")
print(f"Number of Dimensions: {array_2d.ndim}")

https://colab.research.google.com/drive/


In [30]:
#3-D array

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]], dtype = 'int32')

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [31]:
#arange function

a = np.arange(0,10,1)

b = np.arange(0,10,2) #(start, end, skip)

c = np.arange(-10,10, 0.5)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a = np.arange(-30,50,10)
a

array([-30, -20, -10,   0,  10,  20,  30,  40])

In [ ]:
import numpy as np

float_array = np.arange(1,9, dtype='int64').reshape(2, 2, -1)

float_array

In [ ]:
float_array = np.arange(1.5, 10.5, 1,  dtype='float64').reshape(3,3)

print(float_array)

In [33]:
#array full of zeros and ones

zero_array = np.zeros((2,3), dtype='int64')

one_array = np.ones((2,3), dtype='float64')

full_array = np.full((2,2), 99, dtype='int64')

zero_array
one_array
full_array

array([[99, 99],
       [99, 99]])

In [ ]:
import numpy as np


a = np.arange(20,40).reshape(5, 4)
# print(a)

b = np.arange(25, 45).reshape(4, 5)

c = np.matmul(a,b)

# print(np.linalg.det(c))
c

In [ ]:
print(np.linalg.eig(c))

print(np.linalg.norm(c))

print(np.linalg.matrix_rank(c))

In [ ]:
a = np.array([[20,-30], [11,14]])
b = np.array([[5,14], [21,-19]])

print(np.linalg.solve(a,b))  #ax=b => x=b*a^-1

print(np.matmul(np.linalg.inv(a), b))
# print(a)
# print(b)

In [ ]:
a = np.array([1,2,3,4], dtype='int64')

print(a+2)
print(a*2)
print(a**2)
print(a/2)

In [ ]:
angles = np.arange(30,360,30)*np.pi/180 #angles in radians..

sin_values = np.sin(angles)
np.round(sin_values, 2)

In [ ]:
import numpy as np

# Two 1D vectors
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Dot product
result = np.dot(a, b)
print(f"Dot product: {result}")


In [ ]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# Matrix multiplication using @
C = A @ B.T # T = transpose A * transpose(B)
print("Matrix multiplication:\n", C)


In [ ]:
x = np.array([0, np.pi/2, np.pi])
y = np.sin(x)
print("sin(x):", np.round(y))

### Pandas

In [ ]:
https://archive.ics.uci.edu/dataset/53/iris

https://archive.ics.uci.edu/dataset/53/iris

In [ ]:
from IPython.display import Image

# Display an image from a file
Image(url='https://miro.medium.com/v2/resize:fit:1400/0*11IwZmSKXw77eYz5', width=400, height=200)


Link to UCI ML Repo: https://archive.ics.uci.edu/

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load the Iris dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
column_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']
iris_df = pd.read_csv(url, names=column_names)

In [ ]:
iris_df.columns