In [6]:
import numpy as np

array_1d=np.array([1,2,3,4,5])
print(array_1d)
array_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array_2d)



[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
array_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
array_3d
array_3d.ndim

3

In [8]:
print('Frist row of 2D array: ', array_2d[0,:] )

Frist row of 2D array:  [1 2 3]


In [9]:
print('Frist column of 2D array: ', array_2d[:,0] )

Frist column of 2D array:  [1 4 7]


In [ ]:
float_array=np.arange(1.2,10.2, dtype='float64').reshape(3,3)
float_array

array([ 1.2,  2.2,  3.2,  4.2,  5.2,  6.2,  7.2,  8.2,  9.2, 10.2])

In [20]:
one_array=np.ones((2,3), dtype='int32')
one_array

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)